version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform"
      - curl -fsSL https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip -o terraform.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - terraform init -input=false

  build:
    commands:
      - terraform validate
      - terraform plan -out=tfplan

  post_build:
    commands:
      - terraform apply -input=false tfplan
